name: CCT Genesis CI

# Trigger the workflow on every push to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install and cache the Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      # Step 3: Check and test the Rust core library
      - name: Check Rust Core
        run: cargo check --verbose
        working-directory: ./causa_core

      - name: Test Rust Core
        run: cargo test --verbose
        working-directory: ./causa_core

      # Step 4: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
        working-directory: ./causa_py

      # Step 5: Build the Rust FFI library for Python
      # We will use a dedicated build tool for robust builds
      - name: Install maturin for Rust-Python builds
        run: pip install maturin

      - name: Build Rust library with maturin
        run: maturin develop
        working-directory: ./causa_py


      # Step 6: Test the Python package and FFI bridge
      - name: Test Python Package
        run: pytest
        working-directory: ./causa_py
